---
force_update:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: kia_uvo
update:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: kia_uvo
set_navigation:
  target:
  fields:
    latitude:
      required: true
      selector:
        number:
          min: -90
          max: 90
          step: 0.001
          mode: box
    longitude:
      required: true
      selector:
        number:
          min: -180
          max: 180
          step: 0.001
          mode: box
    name:
      required: true
      selector:
        text:
    address:
      required: false
      selector:
        text:
    zip_code:
      required: false
      selector:
        text:
    place_id:
      required: false
      selector:
        text:
capture_svm_image:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: kia_uvo
