force_update: 
  fields: 
    device_id: 
      required: false
      selector: 
        device: 
          integration: kia_uvo
update: 
  fields: 
    device_id: 
      required: false
      selector: 
        device: 
          integration: kia_uvo
